config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('allauth.urls')),
  path("", include("itswill_org.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itswill_org/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns

import datetime

from . import views
from . import api

from .provider import TwitchChatbotProvider

app_name = 'itswill_org'
urlpatterns = [
  path("", views.IndexView.as_view(), name="index"),
  path("pets/", views.PetsView.as_view(), name="pets"),
  path("month/", views.MonthListView.as_view(), name="month_list"),
  path("month/<int:year>/<int:month>/", cache_page(60 * 60)(views.MonthView.as_view()), name="month"),
  
  path("recap/",                                       cache_page(5 * 60)(views.RecapView.as_view()), kwargs = { "year": 0, "month": 0, "username": None }, name="recap"),
  path("recap/<int:year>/",                            cache_page(5 * 60)(views.RecapView.as_view()), kwargs = { "month": 0, "username": None }, name="recap_year"),
  path("recap/<int:year>/<int:month>/",                cache_page(5 * 60)(views.RecapView.as_view()), kwargs = { "username": None }, name = "recap_month"),
  path("recap/all/<str:username>/",                    views.RecapView.as_view(), kwargs = { "year": 0, "month": 0 }, name = "recap_user"),
  path("recap/<int:year>/<str:username>/",             views.RecapView.as_view(), kwargs = { "month": 0 }, name = "recap_year_user"),
  path("recap/<int:year>/<int:month>/<str:username>/", views.RecapView.as_view(), name = "recap_month_user"),
  
  path("recap/redirect/", views.get_recap, name = "recap_redirect"),
  
  path("leaderboard/",                        cache_page(60)(views.LeaderboardView.as_view()), kwargs = { "year": 0, "month": 0 }, name="leaderboard"),
  path("leaderboard/<int:year>/",             cache_page(60)(views.LeaderboardView.as_view()), kwargs = { "month": 0 }, name="leaderboard_year"),
  path("leaderboard/<int:year>/<int:month>/", cache_page(60)(views.LeaderboardView.as_view()), name="leaderboard_month"),
  
  path("leaderboard/<str:name>/",                        cache_page(60)(views.SingleLeaderboardView.as_view()), kwargs = { "year": 0, "month": 0 }, name = "single_leaderboard"),
  path("leaderboard/<int:year>/<str:name>/",             cache_page(60)(views.SingleLeaderboardView.as_view()), kwargs = { "month": 0 }, name = "single_leaderboard_year"),
  path("leaderboard/<int:year>/<int:month>/<str:name>/", cache_page(60)(views.SingleLeaderboardView.as_view()), name = "single_leaderboard_month"),
  
  path("wrapped/", views.Wrapped2025View.as_view(), name="wrapped"),
  path("wrapped/user/<str:username>/", views.Wrapped2025UserView.as_view(), name="wrapped_user"),

  path("wrapped/2024/", cache_page(60)(views.Wrapped2024View.as_view()), name="wrapped_2024"),
  path("wrapped/2024/user/<str:username>/", views.Wrapped2024UserView.as_view(), name="wrapped_2024_user"),
  
  path("wrapped/redirect/", views.get_wrapped, name = "wrapped_redirect"),
  
  path("census/", views.CensusView.as_view(), name="census"),
  path("census/present/", views.CensusPresentationView.as_view(), name="census_present"),
  
  path("pasta/", views.CopyPasteView.as_view(), name="pasta"),
  path("ascii/", views.AsciiView.as_view(), name="ascii"),
  
  path("api/v1/randmsg/",      api.get_random_message_api,              name = "api_random_message"),
  path("api/v1/randuser/",     api.get_random_user_api,                 name = "api_random_user"),
  path("api/v1/randreview/",   api.get_random_letterboxd_review,        name = "api_movie_review"),
  path("api/v1/randclip/",     api.get_random_clip,                     name = "api_random_clip"),
  path("api/v1/pets/",         api.get_pets_message,                    name = "api_pets_message"),
  path("api/v1/recentpet/",    api.get_most_recent_pet,                 name = "api_recent_pet"),
  path("api/v1/petsleft/",     api.get_pets_left,                       name = "api_pets_left"),
  path("api/v1/randgarf/",     api.get_random_garfield,                 name = "api_random_garfield"),
  path("api/v1/five/",         api.get_live_at_five_record,             name = "api_five_record"),
  path("api/v1/totalkc/",      cache_page(10 * 60)(api.get_boss_count), name = "api_total_boss_kc"),
  path("api/v1/recap/",        api.get_recap_data,                      name = "api_get_recap_data"),
  path("api/v1/test/",         api.test_endpoint,                       name = "api_test"),
] + default_urlpatterns(TwitchChatbotProvider)

itswill_org/views.py
import calendar
import datetime
import json
import logging
import typing

from allauth.socialaccount.adapter import get_adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Error
from allauth.socialaccount.providers.oauth2.views import (
    OAuth2Adapter,
    OAuth2CallbackView,
    OAuth2LoginView,
)
from allauth.socialaccount.providers.twitch.views import TwitchOAuth2Adapter
from dateutil import tz
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import FieldDoesNotExist
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import classonlymethod, method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import *
from .tasks import *

logger = logging.getLogger("django")

# Create your views here.


class IndexView(generic.TemplateView):
    template_name = "itswill_org/index.html"


class CensusView(generic.TemplateView):
    template_name = "itswill_org/census.html"


class CensusPresentationView(generic.TemplateView):
    template_name = "itswill_org/census-presentation.html"


class MonthListView(generic.TemplateView):
    template_name = "itswill_org/monthlist.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data["monthly_recaps"] = {}

        for recap in RecapData.objects.filter(month__gte=1, twitch_user=None).all():
            if recap.year not in data["monthly_recaps"]:
                data["monthly_recaps"][recap.year] = {}

            data["monthly_recaps"][recap.year][recap.month] = {
                "month_name": datetime.datetime(
                    recap.year, recap.month, 1, 12, 0, 0
                ).strftime("%B"),
                "recap": recap,
            }

        data["monthly_recaps"] = dict(
            sorted(data["monthly_recaps"].items(), key=lambda kvp: kvp[0])
        )

        for year, month_dict in data["monthly_recaps"].items():
            data["monthly_recaps"][year] = dict(
                sorted(data["monthly_recaps"][year].items(), key=lambda kvp: kvp[0])
            )

        return data


class MonthView(generic.TemplateView):
    template_name = "itswill_org/month.html"

    def dispatch(self, request, year, month, *args, **kwargs):
        try:
            monthlyrecap = RecapData.objects.get(
                year=year, month=month, twitch_user=None
            )
            return super(MonthView, self).dispatch(
                request, year=year, month=month, *args, **kwargs
            )
        except RecapData.DoesNotExist:
            raise Http404("This months data has not been collected yet.")

    def get_context_data(self, year, month, **kwargs):
        data = super().get_context_data(**kwargs)

        try:
            monthlyrecap = RecapData.objects.get(
                year=year, month=month, twitch_user=None
            )
        except RecapData.DoesNotExist:
            logger.error("MISSING MONTHLY RECAP, NOT REDIRECTED BY DISPATCH")
            return data

        localtz = tz.gettz("America/Los_Angeles")
        monthrange = calendar.monthrange(year, month)

        start_date = datetime.datetime(year, month, 1, 0, 0, 0, 1, localtz)
        end_date = datetime.datetime(
            year, month, monthrange[1], 23, 59, 59, 999999, localtz
        )

        data["start_date"] = start_date.strftime("%Y/%m/%d")
        data["end_date"] = end_date.strftime("%Y/%m/%d")

        monthlychatters = RecapData.objects.filter(year=year, month=month).exclude(
            twitch_user=None
        )

        clips = Clip.objects.filter(created_at__range=(start_date, end_date)).order_by(
            "-view_count"
        )

        data["top_clips"] = clips[:10]

        data["clip_count"] = monthlyrecap.count_clips
        data["message_count"] = monthlyrecap.count_messages
        data["clip_views"] = monthlyrecap.count_clip_views
        data["chatter_count"] = monthlyrecap.count_chatters
        data["vod_count"] = monthlyrecap.count_videos

        chatter_list = monthlychatters.order_by("-count_messages")
        clipper_list = monthlychatters.order_by("-count_clips")

        data["top_chatters"] = chatter_list[:10]
        data["top_clippers"] = clipper_list[:10]

        return data


class PetsView(generic.TemplateView):
    template_name = "itswill_org/pets.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data["acquired_pets"] = Pet.objects.filter(acquired=True).order_by("date").all()
        data["unacquired_pets"] = (
            Pet.objects.filter(acquired=False).order_by("name").all()
        )

        data["total_pets"] = Pet.objects.all().count()

        data["drinfo"] = {}

        for pet in data["acquired_pets"]:
            data["drinfo"][pet.name] = {}
            if (pet.killcount_known and pet.drop_rate_known) and (
                not pet.secondary_killcount_needed or pet.secondary_drop_rate_known
            ):
                data["drinfo"][pet.name]["show"] = True
                percent = pet.killcount / pet.drop_rate
                if pet.secondary_killcount_needed:
                    percent += pet.secondary_killcount / pet.secondary_drop_rate
                data["drinfo"][pet.name]["percent"] = percent

                divclass = "no-drop-rate-info"
                if percent < 0.1:
                    divclass = "absurdly-lucky"
                elif percent < 0.333:
                    divclass = "very-lucky"
                elif percent < 0.8:
                    divclass = "lucky"
                elif percent < 1.2:
                    divclass = "on-rate"
                elif percent < 2:
                    divclass = "unlucky"
                elif percent < 3:
                    divclass = "very-unlucky"
                else:
                    divclass = "absurdly-unlucky"

                data["drinfo"][pet.name]["class"] = divclass
            else:
                data["drinfo"][pet.name]["show"] = False
                data["drinfo"][pet.name]["percent"] = 0
                data["drinfo"][pet.name]["class"] = "no-drop-rate-info"

        return data


class RecapView(generic.TemplateView):
    template_name = "itswill_org/recap.html"

    def get_context_data(self, year: int, month: int, username: str, **kwargs):
        start = time.perf_counter()
        logger.info("getting recap view context data")

        data = super().get_context_data(**kwargs)

        data["month_abbr"] = calendar.month_abbr
        all_recaps = {}

        recap_times = (
            RecapData.objects.filter(twitch_user=None)
            .order_by("year", "month")
            .values_list("year", "month")
            .all()
        )
        for y, m in recap_times:
            if y not in all_recaps:
                all_recaps[y] = []
            all_recaps[y].append(m)

        data["all_recaps"] = all_recaps

        logger.info(f"\tFetch overall: {time.perf_counter()-start:.3f}")
        start = time.perf_counter()

        if username is not None:
            username = username.strip()

            try:
                twitchuser = TwitchUser.objects.get(display_name__iexact=username)
            except TwitchUser.DoesNotExist:
                try:
                    twitchuser = TwitchUser.objects.get(login__iexact=username)
                except:
                    raise Http404("That user does not exist or has not chatted.")

            try:
                recap = (
                    RecapData.objects.select_related("twitch_user")
                    .prefetch_related("fragmentgroupcounter_set", "fragmentcounter_set")
                    .select_related("twitch_user")
                    .get(year=year, month=month, twitch_user=twitchuser)
                )
            except RecapData.DoesNotExist:
                raise Http404("No data for that user in this period.")

            data["overall_recap"] = False
            data["recap"] = recap
        else:
            try:
                recap = RecapData.objects.get(year=year, month=month, twitch_user=None)
            except RecapData.DoesNotExist:
                raise Http404("That recap does not exist (yet?).")

            data["overall_recap"] = True
            data["recap"] = recap

        logger.info(f"\tFetch recap: {time.perf_counter()-start:.3f}")
        start = time.perf_counter()

        fragment_group_counters = (
            FragmentGroupCounter.objects.filter(recap=recap)
            .select_related("fragment_group")
            .values_list("fragment_group__group_id", "count")
            .all()
        )
        fragment_counters = (
            FragmentCounter.objects.filter(recap=recap)
            .select_related("fragment")
            .values_list("fragment__group__group_id", "fragment__fragment_id", "count")
            .all()
        )

        logger.info(f"\tLoad fragment counters: {time.perf_counter()-start:.3f}")
        start = time.perf_counter()

        data["fragment_data"] = {
            group_id: {
                "total": count,
                "members": {
                    fragment_id: count
                    for _, fragment_id, count in filter(
                        lambda fcd: fcd[0] == group_id, fragment_counters
                    )
                },
            }
            for group_id, count in fragment_group_counters
        }
        logger.info(f"\tContextify fragment counters: {time.perf_counter()-start:.3f}")
        start = time.perf_counter()

        data["fragment_groups"] = (
            FragmentGroup.objects.order_by("ordering")
            .prefetch_related("fragment_set")
            .all()
        )

        logger.info(f"\tFetch fragments: {time.perf_counter()-start:.3f}")
        return data

itswill_org/templates/itswill_org/base.html
{% load static %}

<!DOCTYPE html>

{% block loadfirst %}{% endblock %}

<link rel="shortcut icon" href="{% static 'favicon.ico' %}">
<link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
<script src="{% static 'util.js' %}"></script>
<script src="{% static 'ajaxhelpers.js' %}"></script>

{% block stylesheets %}{% endblock %}

{% block scripts %}{% endblock %}

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}itswill.{% endblock %}</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

itswill_org/templates/itswill_org/leaderboard.html
{% load static %}
{% load index %}
{% load humanize %}

<div class="leaderboard-item" id="{{ leaderboard_id }}">
  <div class="leaderboard-label" id="{{ leaderboard_id }}-label">
    {% if fg and fg.use_images %}
      {% for frag in fg.fragment_set.all %}
        {% if frag.image %}
          <img class="emote-img" id="{{ frag.fragment_id }}-img" src="{{ frag.image.url }}" title="{{ frag.match }}">
        {% endif %}
      {% endfor %}
    {% else %}
      <div class="leaderboard-label" id="{{ leaderboard_id }}-label">{{ unit }}</div>
    {% endif %}
    {% if recap_data.year == 0 %}
      <div class="leaderboard-note" id="{{ leaderboard_id }}-full-link"><a href="{% url 'itswill_org:single_leaderboard' leaderboard_id %}">Full list</a></div>
    {% else %}
      {% if recap_data.month == 0 %}
      <div class="leaderboard-note" id="{{ leaderboard_id }}-full-link"><a href="{% url 'itswill_org:single_leaderboard_year' recap_data.year leaderboard_id %}">Full list</a></div>
      {% else %}
      <div class="leaderboard-note" id="{{ leaderboard_id }}-full-link"><a href="{% url 'itswill_org:single_leaderboard_month' recap_data.year recap_data.month leaderboard_id %}">Full list</a></div>
      {% endif %}
    {% endif %}
  </div>
  <table class="stat-leaderboard" id="{{ leaderboard_id }}-leaderboard">
    {% if leaderboard %}
    {% for entry in leaderboard|filter_on_not_index:2|firstn:limit %}
      <tr class='leaderboard-table'>
        <td>{{ forloop.counter }}.</td>
        <td>{{ entry.0 }}</td>
        <td>{{ entry.1|intcomma }}</td>
      </tr>
    {% endfor %}
    {% else %}
    <tr class="leaderboard-table">
     <td></td> 
     <td>No data</td>
     <td></td>
    </tr>
    {% endif %}
  </table>
</div>

itswill_org/templates/itswill_org/recap.html
{% extends 'itswill_org/base.html' %}

{% load static %}
{% load index %}
{% load humanize %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'itswill_org/recap.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'itswill_org/recap.js' %}"
  defer
  data-year="{{ recap.year }}"
  data-month="{{ recap.month }}"
  {% if overall_recap %}
  data-getrecapdataurl="{% url 'itswill_org:api_get_recap_data' %}?year={{ recap.year }}&month={{ recap.month }}"
  {% else %}
  data-getrecapdataurl="{% url 'itswill_org:api_get_recap_data' %}?year={{ recap.year }}&month={{ recap.month }}&user={{ recap.twitch_user.user_id }}"
  {% endif %}
  data-overallrecap="{% if overall_recap %}1{% else %}0{% endif %}"
>
</script>
{% endblock %}

{% block title %}The itswill Recap{% endblock %}
    
{% block body %}
<div class="content">
  <div class="section-wrap" id="lookup-form-wrap">
    <div class="section" id="lookup-form">
      <form class="recap-form" action="{% url 'itswill_org:recap_redirect' %}" method="post">
        <input type="hidden" name="year" value="{{ recap.year }}">
        <input type="hidden" name="month" value="{{ recap.month }}">
        <label class="entry-label" id="username-entry-label" for="id_username">Username:</label>
        <input type="text" id="id_username" name="username">
        <input type="submit" class="form-button" id="lookup-submit" value="Find user">
      </form>
    </div>
  </div>
  <div class="section-wrap" id="stats-wrap">
    <div class="section" id="stats">
      <div class="full-section-title">
        <div class="section-title" id="stat-title">
          {% if overall_recap %}
            Overall statistics
          {% else %}
            {{ recap.twitch_user.display_name }}'s statistics
          {% endif %}
        </div>
        <div class="section-subtitle" id="range-subtitle">
          {% if recap.year == 0%}
          All time
          {% else %}
          {% if recap.month == 0 %}
          All of {{ recap.year }}
          {% else %}
          {{ month_abbr|index:recap.month }} {{ recap.year }}
          {% endif %}
          {% endif %}
        </div>
        {% if recap.year == 0 %}
        <div class="section-note" id="leaderboard-link">(<a href="{% url 'itswill_org:leaderboard' %}">Click to see the leaderboards</a>)</div>
        {% else %}
        {% if recap.month == 0 %}
        <div class="section-note" id="leaderboard-link">(<a href="{% url 'itswill_org:leaderboard_year' recap.year %}">Click to see the leaderboards</a>)</div>
        {% else %}
        <div class="section-note" id="leaderboard-link">(<a href="{% url 'itswill_org:leaderboard_month' recap.year recap.month %}">Click to see the leaderboards</a>)</div>
        {% endif %}
        {% endif %}
      </div>
      <table id="stat-table">
        <tr class="stat-item" id="msg-count">
          <td class="stat-label" id="msg-count-label">Messages sent:</td>
          <td class="stat-value" id="msg-count-value">{{ recap.count_messages|intcomma }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="char-count">
          <td class="stat-label" id="char-count-label">Characters sent:</td>
          <td class="stat-value" id="char-count-value">{{ recap.count_characters|intcomma }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="char-count">
          <td class="stat-label" id="char-count-label">Avg. characters/message:</td>
          <td class="stat-value" id="char-count-value">{% if recap.count_messages > 0 %}{{ recap.count_characters|intdivide:recap.count_messages|intcomma }}{% else %}0{% endif %}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="char-time">
          <td class="stat-label" id="char-time-label">Typing time (60 WPM):</td>
          <td class="stat-value" id="char-time-value">{{ recap.count_characters|intdivide:5|time_to_pretty_string:True }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="clip-count">
          <td class="stat-label" id="clip-count-label">Clips created:</td>
          <td class="stat-value" id="clip-count-value">{{ recap.count_clips|intcomma }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="clip-views">
          <td class="stat-label" id="clip-views-label">Views on those clips:</td>
          <td class="stat-value" id="clip-views-value">{{ recap.count_clip_views|intcomma }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="clip-watch">
          <td class="stat-label" id="clip-watch-label">Clip watch time:</td>
          <td class="stat-value" id="clip-watch-value">{{ recap.count_clip_watch|time_to_pretty_string:True }}</td>
          <td></td>
        </tr>
        {% if overall_recap %}
        <tr class="stat-item" id="predictions">
          <td class="stat-label" id="predictions-label">Predictions run:</td>
          <td class="stat-value" id="predictions-value">{{ recap.count_predictions|intcomma }}</td>
          <td></td>
        </tr>
        <tr class="stat-item" id="points-gambled">
          <td class="stat-label" id="points-gambled-label">Channel points gambled:</td>
          <td class="stat-value" id="points-gambled-value">{{ recap.count_points_gambled|intcomma }}</td>
          <td></td>
        </tr>
        {% endif %}
        <tr class="stat-item" id="first-msg-row">
          <td colspan="3">
            <div>
              <table>
                <tr>
                  <td class="stat-label" id="first-msg-label">First message:</td>
                </tr>
                <tr>
                  {% if recap.first_message %}
                  <td colspan="2" class="stat-value" id="first-msg-value">"{{ recap.first_message.message }}"{% if overall_recap %} - {{ recap.first_message.commenter.display_name }}{% endif %}</td>
                  {% else %}
                  <td colspan="2" class="stat-value" id="first-msg-value"><i>None</i></td>
                  {% endif %}
                </tr>
              </table>
            </div>
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr class="stat-item" id="last-msg-row">
          <td colspan="3">
            <div>
              <table>
                <tr>
                  <td class="stat-label" id="last-msg-label">Last message:</td>
                </tr>
                <tr>
                  {% if recap.last_message %}
                  <td colspan="2" class="stat-value" id="last-msg-value">"{{ recap.last_message.message }}"{% if overall_recap %} - {{ recap.last_message.commenter.display_name }}{% endif %}</td>
                  {% else %}
                  <td colspan="2" class="stat-value" id="last-msg-value"><i>None</i></td>
                  {% endif %}
                </tr>
              </table>
            </div>
          </td>
          <td></td>
          <td></td>
        </tr>
      </table>
      <table id="counter-table">
        {% for fg in fragment_groups %}
          {% if fg.show_in_recap %}
          <tr class="stat-item" id="{{ fg.group_id }}">
            <td class="stat-label" id="{{ fg.group_id }}-label">
              {% if fg.use_images %}
              {% for frag in fg.fragment_set.all %}
                {% if frag.image %}
                  <img class="emote-img" id="{{ frag.fragment_id }}-img" src="{{ frag.image.url }}" title="{{ frag.match }}">
                {% endif %}
              {% endfor %}
              {% else %}
                {{ fg.unit }}:
              {% endif %}
            </td>
            
            {% if fg.group_id in fragment_data %}
              {% with counterobj=fragment_data|keyvalue:fg.group_id %}
              <td class="stat-value" id="{{ fg.group_id }}-value">{{ counterobj.total|intcomma }}</td>
              {% endwith %}
            {% else %}
              <td class="stat-value" id="{{ fg.group_id }}-value">0</td>
            {% endif %}
            
            {% if fg.expandable and fg.fragment_set.all|length > 1 %}
              <td class="expand-stat" id="expand-{{ fg.group_id }}" group="{{fg.group_id }}">[+]</td>
            {% else %}
              <td></td>
            {% endif %}
          </tr>
            
          {% if fg.expandable and fg.fragment_set.all|length > 1 %}
          <tr class="stat-breakdown" id="{{fg.group_id}}-breakdown">
            <td colspan="2">
              <div class="stat-breakdown-container">
                <table class="stat-breakdown-table">
                  {% for frag in fg.fragment_set.all %}
                  <tr class="stat-item" id="{{ frag.fragment_id }}">
                    <td class="stat-label" id="{{ frag.fragment_id }}-label">
                      {% if fg.use_images and frag.image %}
                        <img class="emote-img" id="{{ frag.fragment_id }}-img" src="{{ frag.image.url }}" title="{{ frag.match }}">
                      {% else %}
                        <span class="stat-label" id="{{ frag.fragment_id }}-label">{{ frag.pretty_name }}:</span>
                      {% endif %}
                    </td>

                    {% if fg.group_id in fragment_data %}
                      {% with counterobj=fragment_data|keyvalue:fg.group_id %}
                      {% if frag.fragment_id in counterobj.members %}
                        {% with fragval=counterobj.members|keyvalue:frag.fragment_id %}
                        <td class="stat-value" id="{{ frag.fragment_id }}-value">{{ fragval|intcomma }}</td>
                        {% endwith %}
                      {% else %}
                        <td class="stat-value" id="{{ frag.fragment_id }}-value">0</td>
                      {% endif %}
                      {% endwith %}
                    {% else %}
                      <td class="stat-value" id="{{ frag.fragment_id }}-value">0</td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                </table>
              </div>
            </td>
          </tr>
          {% endif %}
          {% endif %}
        {% endfor %}
      </table>
    </div>
  </div>
  <div class="section-wrap" id="links-wrap">
    <div class="section" id="links">
      <div class="full-section-title">
        <div class="section-title" id="links-title">
          QUICK LINKS
        </div>
      </div>
      <div class="link-section">
        <div class="link-section-title">
          Overall Recaps
        </div>
      {% for year, months in all_recaps.items %}
        <div class="main-link">
          {% if year == 0 %}
          <a href="{% url 'itswill_org:recap' %}">All time</a>
          {% else %}
          <a href="{% url 'itswill_org:recap_year' year %}">{{ year }}</a>
          {% endif %}
        </div>

        <div class="sublinks-section">
        {% for month in months %}
          <span class="sublink">
            <a href="{% url 'itswill_org:recap_month' year month %}">{{ month_abbr|index:month }}</a>
          </span>
        {% endfor %}
        </div>
      {% endfor %}
      </div>
      {% if not overall_recap %}
      <div class="link-section">
        <div class="link-section-title">
          {{ recap.twitch_user.display_name}}'s Recaps
        </div>
        {% for year, months in all_recaps.items %}
        <div class="main-link">
          {% if year == 0 %}
          <a href="{% url 'itswill_org:recap_user' recap.twitch_user.login %}">All time</a>
          {% else %}
          <a href="{% url 'itswill_org:recap_year_user' year recap.twitch_user.login %}">{{ year }}</a>
          {% endif %}
        </div>
        <div class="sublinks-section">
          {% for month in months %}
          <span class="sublink">
            <a href="{% url 'itswill_org:recap_month_user' year month recap.twitch_user.login %}">{{ month_abbr|index:month }}</a>
          </span>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}